#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

#
# aliases
#

alias be='bundle exec'

#
# pyenv
#

export PATH="/Users/artur/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

#
# z
#

. `brew --prefix`/etc/profile.d/z.sh

#
# nvm
#

export NVM_DIR=~/.nvm
source $(brew --prefix nvm)/nvm.sh

#
# golang
#

export GOPATH=$HOME/golang
export GOROOT=/usr/local/opt/go/libexec
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$GOROOT/bin

#
# base16 colourscheme
#

# BASE16_SCHEME="default"
#BASE16_SHELL="$HOME/.config/base16-shell/base16-$BASE16_SCHEME.dark.sh"
#[[ -s $BASE16_SHELL ]] && . $BASE16_SHELL


#
# Heroku Toolbelt
#

export PATH="/usr/local/heroku/bin:$PATH"
export LC_ALL=en_US.UTF-8

#
# travis
#

[ -f /Users/artur/.travis/travis.sh ] && source /Users/artur/.travis/travis.sh
